from langchain_core.tools import tool
from datetime import datetime
from pathlib import Path
import subprocess
import os

# -------------------------------
# Project paths (DO NOT CHANGE)
# -------------------------------
PROJECT_ROOT = Path(__file__).parent
TECTONIC_PATH = PROJECT_ROOT / "bin" / "tectonic.exe"


@tool
def render_latex_pdf(latex_content: str) -> str:
    """
    Render a LaTeX document to PDF using Tectonic.

    Args:
        latex_content (str): Full LaTeX document

    Returns:
        str: Absolute path to generated PDF
    """

    # 1️⃣ Verify tectonic exists
    if not TECTONIC_PATH.exists():
        raise RuntimeError(
            f"Tectonic executable not found at: {TECTONIC_PATH}"
        )

    # 2️⃣ Create output directory
    output_dir = PROJECT_ROOT / "output"
    output_dir.mkdir(exist_ok=True)

    # 3️⃣ File names
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    tex_filename = f"paper_{timestamp}.tex"
    pdf_filename = f"paper_{timestamp}.pdf"

    tex_file = output_dir / tex_filename
    tex_file.write_text(latex_content, encoding="utf-8")

    # 4️⃣ Run tectonic (absolute path — critical)
    result = subprocess.run(
        [
            str(TECTONIC_PATH),
            tex_filename,
            "--outdir",
            str(output_dir),
        ],
        cwd=output_dir,
        capture_output=True,
        text=True,
    )

# 5️⃣ Return error to the agent if LaTeX fails
    if result.returncode != 0:
        return (
            f"LaTeX Compilation Failed! Please fix the syntax errors in your LaTeX code and try calling this tool again.\n"
            f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
        )

    final_pdf = output_dir / pdf_filename
    if not final_pdf.exists():
        return "Error: PDF was not generated by Tectonic despite no error code. Check your document structure."

    return str(final_pdf)
